service: pictarium

provider:
  name: aws
  runtime: nodejs8.10
  stage: v1
  region: ${file(./config/aws.json):region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${file(./config/aws.json):s3.alubum_bucket}/*"

functions:
  resize:
    handler: handler.resize
    events:
      - s3:
          bucket: ${file(./config/aws.json):s3.alubum_bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: original/

resources:
  Resources:
    S3BucketStorage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(./config/aws.json):s3.storage_bucket}
