service: pictarium

provider:
  name: aws
  runtime: nodejs6.10
  stage: v1
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::pictarium-photos/*"

functions:
  app:
    handler: handler.app
    timeout: 30
    events:
      - http:
          path: /
          method: get
  resize:
    handler: handler.resize
    events:
      - s3:
          bucket: pictarium-photos
          event: s3:ObjectCreated:*
          rules:
            - prefix: original/

resources:
  Resources:
    S3BucketStorage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pictarium-storage
