service: pictarium

provider:
  name: aws
  runtime: nodejs6.10
  stage: v1
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::qazsato-serverless-s3-sample/*"

functions:
  app:
    handler: handler.app
    timeout: 30
    events:
      - http:
          path: /
          method: get
  resize:
    handler: handler.resize
    events:
      - s3:
          bucket: qazsato-serverless-s3-sample
          event: s3:ObjectCreated:*
          rules:
            - prefix: original/

resources:
  Resources:
    S3BucketStorage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pictarium-storage
    S3BucketPhotos:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pictarium-photos
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - POST
                - GET
                - PUT
                - DELETE
                - HEAD
              AllowedOrigins:
                - "*"
