service: pictarium

provider:
  name: aws
  runtime: nodejs6.10
  stage: v1
  region: ap-northeast-1

functions:
  user:
    handler: handler.user
    timeout: 30
    events:
      - http:
          path: user
          method: get
  list:
    handler: handler.list
    timeout: 30
    events:
      - http:
          path: list
          method: get

resources:
  Resources:
    S3BucketStorage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pictarium-storage
    S3BucketPhotos:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pictarium-photos
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - POST
                - GET
                - PUT
                - DELETE
                - HEAD
              AllowedOrigins:
                - "*"
