service: pictarium

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
  user:
    handler: handler.user
    timeout: 300
    events:
      - http:
          path: user
          method: get

resources:
  Resources:
    S3BucketPhotos:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pictarium-photos-test
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - POST
                - GET
                - PUT
                - DELETE
                - HEAD
              AllowedOrigins:
                - "*"

